import { Link, useParams } from 'react-router-dom'
import { Check, Download, Home, Share2, Ticket } from 'lucide-react'
import { motion } from 'motion/react'
import { Container } from '@/components/ui/Container'
import { Card } from '@/components/ui/Card'
import { Button } from '@/components/ui/Button'
import { getBookings } from '@/services/bookingStore'

export default function Confirmation() {
  const { id } = useParams()
  const booking = getBookings().find((item) => item.id === id) || undefined
  if (!booking) return <Container className="py-24 text-center"><p>Booking not found.</p><Link to="/" className="mt-4 inline-block text-signal-700">Return home</Link></Container>
  const { trip } = booking
  return <div className="min-h-screen bg-paper-dim pb-20"><Container className="py-12"><div className="mx-auto max-w-3xl"><motion.div initial={{ opacity: 0, scale: 0.94 }} animate={{ opacity: 1, scale: 1 }} className="text-center"><span className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-signal-600 text-white shadow-lg shadow-signal-600/20"><Check className="h-8 w-8" /></span><p className="mt-5 text-xs font-semibold uppercase tracking-[0.16em] text-signal-700">Payment successful</p><h1 className="mt-2 font-display text-4xl font-semibold text-ink-950">Booking confirmed.</h1><p className="mt-2 text-ink-500">Your journey is locked in. Keep this ticket handy.</p></motion.div><Card className="mt-8 overflow-hidden"><div className="bg-ink-950 p-6 text-white sm:p-8"><div className="flex items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.15em] text-white/40">NEXTRIP digital ticket</p><p className="mt-2 font-display text-2xl font-semibold">{trip.operator}</p><p className="mt-1 text-sm text-white/50">Booking ID · {booking.id}</p></div><Ticket className="h-7 w-7 text-signal-300" /></div><div className="mt-8 grid grid-cols-[1fr_auto_1fr] items-end gap-4"><div><p className="flap text-2xl font-semibold">{trip.departureTime}</p><p className="text-sm text-white/50">{trip.boardingPoint ?? trip.departureAirport ?? 'Origin'}</p></div><div className="pb-1 text-white/30">→</div><div className="text-right"><p className="flap text-2xl font-semibold">{trip.arrivalTime}</p><p className="text-sm text-white/50">{trip.droppingPoint ?? trip.arrivalAirport ?? 'Destination'}</p></div></div></div><div className="grid gap-6 p-6 sm:grid-cols-3 sm:p-8"><div><p className="text-xs text-ink-400">Passengers</p><p className="mt-1 font-semibold">{booking.passengers.map((p) => p.name).join(', ')}</p></div><div><p className="text-xs text-ink-400">Seats</p><p className="mt-1 font-semibold">{booking.seats.join(', ')}</p></div><div><p className="text-xs text-ink-400">Paid</p><p className="mt-1 font-display text-xl font-semibold">₹{booking.total.toLocaleString('en-IN')}</p></div></div><div className="border-t border-dashed border-paper-line p-6 sm:p-8"><div className="grid gap-4 sm:grid-cols-3"><Button variant="outline" onClick={() => window.print()}><Download className="h-4 w-4" /> Print / save PDF</Button><Button variant="outline" onClick={() => navigator.share?.({ title: 'NEXTRIP ticket', text: `Booking ${booking.id}` }).catch(() => undefined)}><Share2 className="h-4 w-4" /> Share</Button><Button asChild variant="signal"><Link to="/bookings">View my bookings</Link></Button></div></div></Card><div className="mt-5 text-center"><Button asChild variant="ghost"><Link to="/"><Home className="h-4 w-4" /> Back to home</Link></Button></div></div></Container></div>
}
