import { useState } from 'react'
import { Link } from 'react-router-dom'
import { Bell, LogOut, Mail, ShieldCheck, UserRound } from 'lucide-react'
import { motion } from 'motion/react'
import { Container } from '@/components/ui/Container'
import { Card } from '@/components/ui/Card'
import { Button } from '@/components/ui/Button'
import { getUser, logout } from '@/services/authStore'

export default function Profile() {
  const user = getUser()
  const [saved, setSaved] = useState(false)
  if (!user) return <Container className="py-24 text-center"><h1 className="font-display text-2xl font-semibold">Your profile is waiting.</h1><p className="mt-2 text-sm text-ink-500">Sign in to manage your NEXTRIP account.</p><Button asChild className="mt-6"><Link to="/login">Sign in</Link></Button></Container>
  return <div className="min-h-screen bg-paper-dim pb-20"><Container className="py-10"><motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}><p className="text-xs font-semibold uppercase tracking-[0.15em] text-signal-700">Account</p><h1 className="mt-2 font-display text-3xl font-semibold">Your profile</h1><p className="mt-1 text-sm text-ink-500">Manage your identity and travel preferences.</p></motion.div><div className="mt-8 grid gap-6 lg:grid-cols-[1fr_340px]"><Card className="p-6 sm:p-8"><div className="flex items-center gap-4"><span className="flex h-14 w-14 items-center justify-center rounded-2xl bg-ink-950 font-display text-xl font-semibold text-signal-300">{user.name.charAt(0).toUpperCase()}</span><div><h2 className="font-display text-xl font-semibold">{user.name}</h2><p className="text-sm text-ink-500">{user.email}</p></div></div><div className="mt-8 grid gap-4 sm:grid-cols-2"><label><span className="text-xs font-medium text-ink-500">Full name</span><div className="relative mt-1.5"><UserRound className="absolute left-3 top-3 h-4 w-4 text-ink-400" /><input defaultValue={user.name} className="h-11 w-full rounded-xl border border-paper-line bg-white pl-10 pr-3 text-sm outline-none focus:border-signal-500" /></div></label><label><span className="text-xs font-medium text-ink-500">Email</span><div className="relative mt-1.5"><Mail className="absolute left-3 top-3 h-4 w-4 text-ink-400" /><input readOnly value={user.email} className="h-11 w-full rounded-xl border border-paper-line bg-paper-dim pl-10 pr-3 text-sm text-ink-500 outline-none" /></div></label></div><Button className="mt-6" onClick={() => { setSaved(true); window.setTimeout(() => setSaved(false), 1800) }}>{saved ? 'Saved ✓' : 'Save changes'}</Button></Card><div className="space-y-4"><Card className="p-6"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 text-signal-600" /><div><h2 className="font-display font-semibold">Account security</h2><p className="mt-1 text-xs leading-relaxed text-ink-500">Passwords are not stored by NEXTRIP in browser storage. Use your authentication provider to manage credentials.</p></div></div></Card><Card className="p-6"><div className="flex items-start gap-3"><Bell className="mt-0.5 h-5 w-5 text-signal-600" /><div><h2 className="font-display font-semibold">Travel updates</h2><p className="mt-1 text-xs leading-relaxed text-ink-500">Keep booking and departure notifications enabled for a smoother journey.</p></div></div></Card><Button variant="outline" className="w-full" onClick={logout}><LogOut className="h-4 w-4" /> Sign out</Button></div></div></Container></div>
}
